int8 straight # joystick value in front/back direction (-100 ~ +100)
int8 turn # joystick value in left/right direction (-100 ~ +100)
---
int32 success  # number of bytes written to the interface
string message # informational, e.g. for error messages
